export const GET_HOME = 'GET_HOME';
export const GET_DETAIL='GET_DETAIL';
export const CHANGE_SHOPFLAG='CHANGE_SHOPFLAG';
export const CHANGE_SHOPDATA='CHANGE_SHOPDATA';
export const TAB_SHOPBTN='TAB_SHOPBTN';
export const PUSH_GOODS_DETAIL='PUSH_GOODS_DETAIL';
